name: Sync GFWList and Add Custom Sites

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 自动运行
  workflow_dispatch:     # 允许手动触发

jobs:
  sync-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Fetch official GFWList
        run: |
          curl -o gfwlist.txt https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

      - name: Decode GFWList and custom sites
        run: |
          base64 --decode gfwlist.txt > gfwlist_decoded.txt
          base64 --decode custom.txt > custom_decoded.txt

      - name: Add custom sites
        run: |
          cat custom_decoded.txt >> gfwlist_decoded.txt

      - name: Encode GFWList
        run: |
          base64 gfwlist_decoded.txt > gfwlist.txt

      - name: Clean decoded files
        run: |
          rm -f gfwlist_decoded.txt custom_decoded.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "Jay-Young"
          git config --global user.email "8641055+Jay-Young@users.noreply.github.com"
          git add gfwlist.txt
          git commit -m "Automated update: Sync GFWList and add custom sites"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/Jay-Young/gfwlist.git
          git push origin main
